# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95ae78623681af51ebf6b2d4c9cdb13ce03b14dacc901c05c2ba7f047723ed9fff5b9a1455656c9fedafd6d6cf9d1114065646e7964cabb30e886e1dba326d68

test:
  secret_key_base: 059bbb7d4f430c53fd0781f8d5168755f5f0fd36a147652a37d199139a4ef7e4502c92b5b70a998744685e6237c7776f2b23721ebc9f2770f5f44a6b50148134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
